config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    get "search" => "users#search"
  end

  resources :books, only: [:show, :create, :index, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :chats, only: [:show, :create, :destroy]

  resources :groups, except: [:destroy] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  get "tag_searches/search" => "tag_searches#search"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  has_many :group_users, dependent: :destroy

  validates :name, uniqueness: { scope: :name }, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @thisweek_book = @books.created_thisweek
    @lastweek_book = @books.created_lastweek
  end

  def index
    @user = User.all
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path
    else
      render :edit
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を指定してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
    </tr>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(100,100) %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
        <td><%= user.followers.count %> フォロワー</td>
        <td><%= render 'relationships/btn', user: user, options: { class: "follow-link" } %></td>
      </tr>
    <% end %>
  </thead>
</table>

app/views/users/_search.html.erb
<h2>検索結果</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-5 mx-auto">
      <h2>User info</h2>

 <!--バリデーション-->
      <% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

<!--ユーザー詳細-->
      <%= form_with model: @user do |f| %>
      <div class="form-group">
        <label for="user_name" class="form-label">Name</label>
        <%= f.text_field :name, autofocus: true, id: "user_name", class: 'form-control' %>
      </div>
      <div class="form-group">
        <label for="profile_image" class="form-label">Image</label><br>
        <%= f.file_field :profile_image, accept: "image/*", id: "profile_image" %>
      </div>
      <div class="form-group">
        <label for="user_introduction" class="form-label">Introduction</label>
        <%= f.text_area :introduction, id: "user_introduction", class: 'form-control' %>
        <%= f.submit 'Update User', class: 'btn btn btn-secondary my-3' %>
      </div>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

<!--テンプレート-->
    <div class="col-md-3">
      <%= render 'books/book', new_book: @new_book, user: current_user %>
    </div>


<!--usersの一覧-->
    <div class="col-md-8 offset-md-1">
      <%= link_to "グループを作成する", new_group_path %> |
      <%= link_to "グループ一覧", groups_path %>
      <h2>Users</h2>
        <%= render 'users/index', users: @user %>
    </div>

  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

<!--テンプレート-->
    <div class="col-md-3">
      <%= render 'books/book', new_book: @new_book, user: @user %>
    </div>

<!--usersの詳細-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
       <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <%= render 'books/index', books: @books %>
        </tbody>
      </table>

<!--投稿数検索-->
      <%= form_with url:user_search_path(@user), method: :get, local: false, class: "mb-3" do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class: "btn btn-primary" %>
      <% end %>

      <div id="search_result", class: "mb-5">
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>

<!--一週間の投稿数一覧-->
      <h2>投稿数の前日比・前週比</h2>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>６日前</th>
            <th>５日前</th>
            <th>４日前</th>
            <th>３日前</th>
            <th>２日前</th>
            <th>１日前</th>
            <th>今日</th>
          </tr>
          <tr>
            <td><%= @books.created_6day_ago.count %></td>
            <td><%= @books.created_5day_ago.count %></td>
            <td><%= @books.created_4day_ago.count %></td>
            <td><%= @books.created_3day_ago.count %></td>
            <td><%= @books.created_2day_ago.count %></td>
            <td><%= @yesterday_book.count %></td>
            <td><%= @today_book.count %></td>
          </tr>
        </thead>
      </table>

<!--一週間の投稿数グラフ-->
      <div>
        <canvas id="myChart"></canvas>
      </div>

      <script>
        $(document).on('turbolinks:load', function () {
          const ctx = document.getElementById('myChart');

          new Chart(ctx, {
            type: 'line',
            data: {
              labels: ['６日前', '５日前', '４日前', '３日前', '２日前', '１日前', '今日'],
              datasets: [{
                label: '投稿した本の数',
                data: [
                  <%= @books.created_6day_ago.count %>,
                  <%= @books.created_5day_ago.count %>,
                  <%= @books.created_4day_ago.count %>,
                  <%= @books.created_3day_ago.count %>,
                  <%= @books.created_2day_ago.count %>,
                  <%= @yesterday_book.count %>,
                  <%= @today_book.count %>
                  ],
                tension: 0.5,
                borderColor: '#6a5acd',
                borderWidth: 3
              }]
            },
            options: {
              title: {
          display: true,
          text: '７日間の投稿数の比較投稿した本の数'
        },
              scales: {
                y: {
                   suggestedMin: 0,
                   suggestedMax: 10
                },
              },
            }
          });
        });
      </script>


<!--前日比・前週比の投稿-->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
          <tr>
            <td><%= @today_book.count %></td>
            <td><%= @yesterday_book.count %></td>
            <td>
              <% if @yesterday_book.count == 0 %>
                前日の投稿が0のため計算できません
              <% else %>
                <% @comparison_yesterday = @today_book.count / @yesterday_book.count.to_f %>
                <%= (@comparison_yesterday*100).round %>%
              <% end %>
            </td>
          </tr>
        </thead>
      </table>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
          <tr>
            <td><%= @thisweek_book.count %></td>
            <td><%= @lastweek_book.count %></td>
            <td>
              <% if @lastweek_book.count == 0 %>
                <p>前週の投稿なし</p>
              <% else %>
                <% @comparison_lastweek = @thisweek_book.count / @lastweek_book.count.to_f %>
                <%= (@comparison_lastweek*100).round %>%
              <% end %>
            </td>
          </tr>
        </thead>
      </table>
    </div>

  </div>
</div>