config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    get "search" => "users#search"
  end

  resources :books, only: [:show, :create, :index, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  resources :chats, only: [:show, :create, :destroy]

  resources :groups, except: [:destroy] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  get "tag_searches/search" => "tag_searches#search"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :week_favorites, -> { where(created_at: 1.week.ago.beginning_of_day..Time.current.end_of_day) }
  has_many :view_counts, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }
  scope :created_thisweek, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_lastweek, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  scope :latest, -> {order(created_at: :desc)}
  scope :star_count, -> {order(star: :desc)}

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end
  end

  def index
    @new_book = Book.new
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    if params[:latest]
      @books = Book.latest
    elsif params[:star_count]
      @books = Book.star_count
    else
      @books = Book.includes(:favorites).sort_by { |book| -book.favorites.where(created_at: from...to).count }
    end
  end

  def create
    @new_book = Book.new(book_params)
    @new_book.user_id = current_user.id
    if @new_book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@new_book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :tag)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<!--ユーザー情報-->
  <div class="col">
  <h2>User info</h2>

  <% if user %>
    <%= image_tag user.get_profile_image(100,100) %>
  <% else %>
    <%= image_tag current_user.get_profile_image(100,100) %>
  <% end %>

    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
          <th>
            <% if user %>
              <%= user.name %>
            <% else %>
              <%= current_user.name %>
            <% end %>
          </th>
        </tr>
        <tr>
          <th>introduction</th>
          <th>
            <% if user %>
              <%= user.introduction %>
            <% else %>
              <%= current_user.introduction %>
            <% end %>
          </th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%= link_to user.followings.count, user_followings_path(user) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to user.followers.count, user_followers_path(user) %></th>
        </tr>
      </tbody>
    </table>

  </div>

  <% if current_user != user %>
    <%= render 'relationships/btn', user: user, options: { class: ""} %>
    <!--current_user != user &&は後で消す-->
    <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
      <%= link_to 'chatを始める', chat_path(user.id), class: "m-2" %>
    <% end %>
  <% else %>
    <% unless user.guest_user? %>
    <%= link_to edit_user_path(user.id) do %>
      <button type="button" class="btn btn-outline-secondary btn-block">
        <i class="fa-solid fa-user-gear"></i>
      </button>
    <% end %>
    <% end %>
  <% end %>


<!--投稿フォーム-->
  <div class="col">
    <h2 class="mt-4">New book</h2>
    <%= form_with model: new_book, url:'/books', method: :post do |f| %>
      <div>
        <label for="book_title" class="form-label">Title</label>
        <%= f.text_field :title, id: "book_title", class: 'form-control' %><br>
        <label for="book_opinion" class="form-label">Opinion</label><br>
        <%= f.text_area :body, id: "book_opinion", class: 'form-control' %><br>
        <label for="tag" class="form-label">Tag</label><br>
        <%= f.text_field :tag, id: "book_tag", class: 'form-control' %><br>
      </div>

      <div id="star">
        <%= f.label :star %>
        <%= f.hidden_field :star, id: :review_star, class: "form-control" %>
        <div id="post_raty"></div>
      </div>
      <script>
        $(document).on('turbolinks:load', function() {
          let elem = document.querySelector('#post_raty');
          if(elem == null) return;

          elem.innerHTML = ""
          let opt = {
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'book[star]',
          };
          raty(elem, opt);
        });
      </script>

      <%= f.submit 'Create Book', class: 'btn btn btn-success mb-3 mt-3' %>
    <% end %>
  </div>

app/views/books/_index.html.erb
<% books.each do |book| %>
  <tr id="book_<%= book.id %>">
  <td>
    <%= link_to user_path(book) do %>
      <%= image_tag book.user.get_profile_image(100,100) %>
    <% end %>
  </td>
  <td><%= link_to book.title, book_path(book) %></td>
  <td><%= book.body %></td>
  <td>
    <% if book.tag.present? %>
      <%= link_to book.tag, tag_searches_search_path(content: book.tag) %>
    <% end %>
  </td>
  <td class="favorite-btn">
    <%= render 'favorites/favorite-btn', book: book %>
  </td>
  <td><%= render "books/static_rate", book: book %></td>
  <td>閲覧数 <%= book.view_counts.count %></td>
  </tr>
<% end %>

app/views/books/_static_rate.html.erb
<div id="star_<%= book.id %>"></div>
<script>
        $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#star_<%= book.id %>');
        if(elem == null) return;

        elem.innerHTML = ""
        let opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          score: "<%= book.star %>",
          readOnly: true,
        };
        raty(elem, opt);
      });
</script>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-5 mx-auto">
      <h1>Editing Book</h1>

<!--バリデーション-->
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>


<!--編集フォーム-->
      <%= form_with model: @book do |f| %>
        <label for="book_title" class="form-label">Title</label><br>
        <%= f.text_field :title,autofocus: true, id: "book_title", class: 'form-control' %><br>
        <label for="book_opinion" class="form-label">Opinion</label><br>
        <%= f.text_area :body, id: "book_opinion", class: 'form-control' %><br>

        <%= render "books/static_rate", book: @book %>

        <%= f.submit 'Update Book', class: 'btn btn btn-success mb-3 mt-3' %>
      <% end %>

      <%= link_to 'Show', book_path(@book) %> |
      <%= link_to 'Back', books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">

<!--バリデーション-->
  <% if @new_book.errors.any? %>
    <h3><%= @new_book.errors.count %>errors prohibited this obj from being saved:</h3>
    <ul>
      <% @new_book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>


  <div class="row">

<!--テンプレート-->
    <div class="col-md-3">
      <%= render 'book', new_book: @new_book, user: current_user %>
    </div>

<!--Booksの投稿一覧-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= link_to "新しい順", books_path(latest: 'true') %>
      |
      <%= link_to "評価の高い順", books_path(star_count: 'true') %>

      <table class="table table-hover">
        <thead>
          <tr>
            <th colspan="2">Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <%= render 'books/index', books: @books %>
        </tbody>
      </table>
    </div>

  </div>

</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">

  <div class="row">

<!--テンプレート-->
    <div class="col-md-3">
      <%= render 'book', new_book: @new_book, user: @book.user %>
    </div>

<!--Booksの詳細-->
    <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>

      <table class="table table-hover">
        <tr id="book_<%= @book.id %>">
          <td>
            <%= link_to user_path(@book.user_id) do %>
              <%= image_tag @book.user.get_profile_image(100,100) %><br>
              <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td class="favorite-btn">
            <%= render 'favorites/favorite-btn', book: @book %>
          </td>
          <td><%= render "books/static_rate", book: @book %></td>
          <td>閲覧数 <%= @book.view_counts.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path, class: 'btn btn btn-success mb-3' %></td>
            <td><%= link_to 'Destroy', book_path, method: :delete, "data-confirm" => "本当に削除しますか？", class: 'btn btn btn-danger mb-3' %></td>
          <% end %>
        </tr>
      </table>
    </div>

  </div>

</div>